name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Unit tests
        run: npm run test:unit
      - name: Build for production
        run: npm run serve -- --mode production
      - name: E2E tests
        run: npx cypress run
