name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Unit tests
        run: npm run test:unit
      - name: E2E tests
        uses: cypress-io/github-action@v1
        with:
          start: npm run serve -- --mode production
          wait-on: http://localhost:8080
