name: Newman Run

on:
  push:
    branches:
      - master

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - run: npm install
      - uses: matt-ball/newman-action@master
        with:
          collection: ./tests/PostmanTrelloCollections.json
          environment: ./tests/TrelloEnv.json
