name: Newman Run

on:
  push:
    branches:
      - master

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@0.0.28
        with:
          collection: ./tests/PostmanTrelloCollections.json
          environment: ./tests/TrelloEnv.json
